DEFAULT_CONFIG = {
    "agent_llm_model": "qwen3.6-plus",
    "graph_llm_model": "qwen3.6-plus",
    "agent_llm_provider": "anthropic",
    "graph_llm_provider": "anthropic",
    "agent_llm_temperature": 0.1,
    "graph_llm_temperature": 0.1,
    "base_url": "https://new.samerwang.dpdns.org",
    "api_key": "",
    "anthropic_api_key": "sk-he9z9G1gu5374yAc6K6ua5sCVXSqc3U3qhnltO0Ls8GKf0aQ",
    "qwen_api_key": "",
    "minimax_api_key": "",
    "sohu_api_key": "",
    "trial_api_key": "sk-17302f529af246608b234120fa46583a",
    "trial_base_url": "https://api.deepseek.com",
    "trial_model": "deepseek-chat",
    "custom_api_key": "",
    "custom_mode": "openai",
    "custom_base_url": "",
    "custom_endpoint_url": "",
    "custom_model": "gpt-4o",
    "custom_headers_template": '{"Authorization":"Bearer {{api_key}}","Content-Type":"application/json"}',
    "custom_body_template": '{"model":"{{model}}","messages":{{messages_json}},"temperature":{{temperature}}}',
    "custom_response_path": "choices.0.message.content",
}
